import { tenant } from '@/config/tenant';
import { buildAbsoluteUrl, siteHost } from '@/config/site';

const lines = (...values: string[]) => values.join('\n');

export const getLlmsTxt = (): string =>
  lines(
    '---',
    `Last-Updated: ${new Date().toISOString().slice(0, 10)}`,
    'License: CC-BY-4.0',
    'See-Also: /llms-full.txt',
    `Cite-As: "${tenant.name} (${siteHost})"`,
    '---',
    '',
    `# ${tenant.name}`,
    '',
    `> ${tenant.tagline} with EU-wide delivery, loyalty rewards, and a tobacco-free nicotine pouch catalogue.`,
    '',
    '## About',
    '',
    `${tenant.name} (${siteHost}) is a European nicotine pouch storefront focused on tobacco-free oral products, honest buying guides, and fast fulfilment. The site combines a live catalogue, strength/flavour browsing, and editorial explainers for adult users.`,
    '',
    '## Key Store Pages',
    '',
    `- Homepage: ${buildAbsoluteUrl('/')}`,
    `- Nicotine pouches catalog: ${buildAbsoluteUrl('/nicotine-pouches')}`,
    `- Brands directory: ${buildAbsoluteUrl('/brands')}`,
    `- Product index: ${buildAbsoluteUrl('/products')}`,
    `- Beginner's guide: ${buildAbsoluteUrl('/beginners')}`,
    `- FAQ: ${buildAbsoluteUrl('/faq')}`,
    `- Shipping: ${buildAbsoluteUrl('/shipping')}`,
    `- Returns: ${buildAbsoluteUrl('/returns')}`,
    `- Contact: ${buildAbsoluteUrl('/contact')}`,
    `- Rewards: ${buildAbsoluteUrl('/rewards')}`,
    '',
    '## Browse by Flavour',
    '',
    `- Mint: ${buildAbsoluteUrl('/products/flavor/mint')}`,
    `- Berry: ${buildAbsoluteUrl('/products/flavor/berry')}`,
    `- Citrus: ${buildAbsoluteUrl('/products/flavor/citrus')}`,
    `- Fruit: ${buildAbsoluteUrl('/products/flavor/fruit')}`,
    `- Coffee: ${buildAbsoluteUrl('/products/flavor/coffee')}`,
    `- Tropical: ${buildAbsoluteUrl('/products/flavor/tropical')}`,
    '',
    '## Browse by Strength',
    '',
    `- Light: ${buildAbsoluteUrl('/products/strength/light')}`,
    `- Normal: ${buildAbsoluteUrl('/products/strength/normal')}`,
    `- Strong: ${buildAbsoluteUrl('/products/strength/strong')}`,
    `- Extra Strong: ${buildAbsoluteUrl('/products/strength/extra-strong')}`,
    `- Super Strong: ${buildAbsoluteUrl('/products/strength/super-strong')}`,
    '',
    '## Editorial & Comparison Data',
    '',
    `- Brand comparison data: ${buildAbsoluteUrl('/nicotine-pouch-brands-compared')}`,
    `- Nicotine strength chart: ${buildAbsoluteUrl('/nicotine-strength-chart')}`,
    `- Flavour guide: ${buildAbsoluteUrl('/nicotine-pouch-flavours')}`,
    `- Nicotine reduction guide: ${buildAbsoluteUrl('/nicotine-reduction-guide')}`,
    '',
    '## Shipping & Store Policy',
    '',
    `- Currency: ${tenant.currencyCode}`,
    `- Free shipping threshold: €${tenant.freeShippingThreshold}`,
    `- Support email: ${tenant.supportEmail}`,
    '- Age requirement: 18+',
    '',
    '## Sitemap',
    '',
    `${buildAbsoluteUrl('/sitemap-index.xml')}`,
    '',
  );

export const getLlmsFullTxt = (): string =>
  lines(
    `# ${tenant.name} — Extended Reference for AI Systems`,
    '',
    `> This document gives a fuller reference for ${tenant.name}. For the short version, see ${buildAbsoluteUrl('/llms.txt')}.`,
    '',
    '## Nicotine Pouch Basics',
    '',
    '- Tobacco-free nicotine pouches are placed between the upper lip and gum.',
    '- They do not involve combustion, smoke, or vapour.',
    '- Common variables when comparing products are strength, pouch format, flavour, moisture level, and price per can.',
    '',
    '## Strength Guide',
    '',
    '| Category | Typical range | Best for |',
    '| --- | --- | --- |',
    '| Light | 1–4 mg/pouch | Beginners and light users |',
    '| Normal | 4–6 mg/pouch | Daily users who want balance |',
    '| Strong | 6–12 mg/pouch | Experienced users |',
    '| Extra Strong | 12–20 mg/pouch | High-tolerance users |',
    '| Super Strong | 20 mg+ | Very high tolerance only |',
    '',
    '## Format Guide',
    '',
    '| Format | Typical profile |',
    '| --- | --- |',
    '| Mini | Small, discreet, lighter feel under the lip |',
    '| Slim | Most common format, balanced comfort and flavour |',
    '| Large/Regular | Higher pouch volume and fuller fit |',
    '',
    '## Storefront Paths',
    '',
    `- Homepage: ${buildAbsoluteUrl('/')}`,
    `- Catalog: ${buildAbsoluteUrl('/nicotine-pouches')}`,
    `- Brands: ${buildAbsoluteUrl('/brands')}`,
    `- Products: ${buildAbsoluteUrl('/products')}`,
    `- Blog hub: ${buildAbsoluteUrl('/blog')}`,
    `- FAQ: ${buildAbsoluteUrl('/faq')}`,
    '',
    '## High-Value Buying Guides',
    '',
    `- How to choose your strength: ${buildAbsoluteUrl('/blog/how-to-choose-your-strength')}`,
    `- What are nicotine pouches?: ${buildAbsoluteUrl('/blog/what-are-nicotine-pouches')}`,
    `- Nicotine pouch ingredients explained: ${buildAbsoluteUrl('/blog/nicotine-pouch-ingredients-explained')}`,
    `- Complete European buying guide: ${buildAbsoluteUrl('/blog/nicotine-pouch-buying-guide-europe')}`,
    `- Nicotine pouches legal in Europe: ${buildAbsoluteUrl('/blog/nicotine-pouches-legal-europe-2026')}`,
    '',
    '## Common Comparison Paths',
    '',
    `- ZYN vs VELO: ${buildAbsoluteUrl('/blog/zyn-vs-velo-2026')}`,
    `- ZYN vs LOOP: ${buildAbsoluteUrl('/blog/zyn-vs-loop-2026')}`,
    `- VELO vs LOOP: ${buildAbsoluteUrl('/blog/velo-vs-loop-2026')}`,
    `- Nicotine pouches vs cigarettes: ${buildAbsoluteUrl('/blog/nicotine-pouches-vs-cigarettes')}`,
    `- Nicotine pouches vs vaping: ${buildAbsoluteUrl('/blog/nicotine-pouches-vs-vaping')}`,
    '',
    '## Store Identity',
    '',
    `- Storefront: ${buildAbsoluteUrl('/')}`,
    `- Site host: ${siteHost}`,
    `- Brand name: ${tenant.name}`,
    `- Legal name: ${tenant.legalName}`,
    `- Support: ${tenant.supportEmail}`,
    `- Free shipping threshold: €${tenant.freeShippingThreshold}`,
    `- Rewards program: ${tenant.loyaltyProgramName}`,
    '',
    '## Sitemap',
    '',
    `${buildAbsoluteUrl('/sitemap-index.xml')}`,
    '',
  );
