-- Product Description Quality Sweep - Batch 2
-- Generated: 2026-03-29
-- Total products: 100 products with null descriptions
-- Target: 80-150 word descriptions with flavor, strength, format, and target user info

-- Product: Its RIPS Blackcurrant Nicotine Strips 0.5mg
UPDATE products SET description = 'Its RIPS Blackcurrant delivers a smooth introduction to nicotine pouches with its ultra-light 0.5mg strength. These slim dissolvable strips feature a bold blackcurrant flavour that blends tart berry notes with subtle sweetness, making them ideal for beginners or those seeking minimal nicotine intake. Each can contains 10 portions for convenient, discreet use throughout your day. The slim format fits comfortably between your gum and lip, dissolving gradually to release flavour without any visible residue. Perfect for exploring the world of nicotine pouches without commitment, or for experienced users who prefer low-dose relaxation.' WHERE id = '1644af33-23d3-497a-9d27-d222c9336038';

-- Product: Its RIPS Fresh Mint Nicotine Strips 0.5mg
UPDATE products SET description = 'Its RIPS Fresh Mint nicotine strips offer a crisp, refreshing experience at just 0.5mg strength—ideal for those new to nicotine pouches or seeking gentler use. The invigorating mint flavour provides an instant coolness that clears the palate whilst delivering consistent, prolonged nicotine release. With 10 slim portions per can, these strips dissolve slowly without any mess or visible residue, making them perfect for work, travel, or social situations. The ultra-low strength ensures a smooth, non-overwhelming experience even for first-time users, whilst the premium flavour keeps you coming back for more.' WHERE id = 'c9b88b08-a61c-475a-bb34-5b4cfe04998b';

-- Product: Its RIPS Ice Mint Nicotine Strips 0.5mg
UPDATE products SET description = 'Its RIPS Ice Mint strips combine a frosty, intensely cooling mint experience with ultra-light 0.5mg nicotine—perfect for beginners and casual users. These slim, dissolvable pouches deliver an arctic blast of flavour that lingers pleasantly whilst you work or relax. Each can provides 10 portions, offering flexibility and affordability for daily use. The gentle nicotine strength makes these an excellent gateway product, allowing you to experience the ritual of pouches without any harsh effects. Ideal for mint enthusiasts seeking simplicity, discretion, and a refreshing boost throughout your day.' WHERE id = '590ccdff-a9c4-418e-becb-9ad18b002a9f';

-- Product: Its RIPS Mango Nicotine Strips 0.5mg
UPDATE products SET description = 'Its RIPS Mango strips transport you to tropical flavours with a zesty, fruity profile at just 0.5mg nicotine strength. These slim pouches are perfect for newcomers to nicotine products, delivering smooth, subtle nicotine release without overwhelming intensity. With 10 portions per can, each strip dissolves cleanly against your gum, providing consistent flavour throughout its duration. The mango profile balances sweetness with bright citrus undertones, offering a unique alternative to traditional mint varieties. Ideal for daytime use, these strips won't stain your teeth or leave residue, making them an excellent choice for professional environments and social settings.' WHERE id = '5f627f9e-8b4f-446e-b4ec-8cdf144ab468';

-- Product: Its RIPS Strawberry Kiwi Nicotine Strips 0.5mg
UPDATE products SET description = 'Its RIPS Strawberry Kiwi strips blend two bright berry flavours into a refreshing, complex taste experience at an approachable 0.5mg strength. These slim dissolvable pouches are crafted for beginners and light users seeking a fruity alternative to mint dominance. Each can delivers 10 portions of smooth, clean-dissolving pouches that release flavour gradually without residue or staining. The strawberry provides sweetness whilst kiwi adds a subtle tartness, creating a balanced, naturally-inspired profile. Perfect for daytime use or whenever you want a flavourful pick-me-up that's discreet enough for any environment.' WHERE id = '79dce007-cfd3-4b8a-985c-7657ed0762cd';

-- Product: Its RIPS Watermelon Nicotine Strips 0.5mg
UPDATE products SET description = 'Its RIPS Watermelon strips offer summer-inspired refreshment with a crisp, juicy flavour profile at the gentlest 0.5mg nicotine strength. These slim pouches dissolve cleanly without residue, making them ideal for professionals and first-time users alike. With 10 portions per can, you'll enjoy consistent, natural-tasting flavour delivery throughout each pouch's duration. The watermelon profile captures both the sweet core and refreshing notes of ripe melons, providing a unique taste that stands apart from traditional mint varieties. Perfect for those who appreciate fruity complexity alongside gentle, steady nicotine delivery in a completely discreet format.' WHERE id = 'e34c2512-1870-4bf4-90ba-be669f17b1c4';

-- Product: LEO Strawberry Kiwi Lime Zero
UPDATE products SET description = 'LEO Strawberry Kiwi Lime Zero delivers tropical, fruity satisfaction at zero nicotine, making it the perfect choice for those seeking the ritual and flavour without nicotine. This slim pouch format provides 20 portions per can, delivering extended sensory pleasure throughout your day. The three-fruit blend—strawberry sweetness, kiwi tartness, and lime brightness—creates a complex, naturally-inspired profile that never feels artificial. Ideal for nicotine-free lifestyles, social situations where alternatives are welcomed, or those gradually reducing intake. The premium flavour ensures you're not sacrificing taste for zero nicotine, with smooth mouthfeel and clean dissolution.' WHERE id = '8cc41b70-145e-4cf7-afbb-07cef0a997a1';

-- Product: LEO Blue Razz Zero
UPDATE products SET description = 'LEO Blue Razz Zero captures the tart, electrifying burst of blue raspberry candy in a zero-nicotine pouch designed for flavour enthusiasts. These slim portions dissolve smoothly against your gum, delivering consistent berry-and-sour notes without any harsh edges. With 20 portions per can, you'll enjoy extended, reliable performance throughout your day. Perfect for those exploring nicotine-free alternatives, younger users, or experienced users who enjoy mixing zero-nicotine varieties with stronger options. The bold, unmistakable blue razz profile provides genuine candy-like satisfaction whilst maintaining the discreet format that makes pouches so convenient.' WHERE id = 'd1932e7a-e713-4547-ad94-8731410a1cd6';

-- Product: LEO Watermelon Ice Zero
UPDATE products SET description = 'LEO Watermelon Ice Zero combines refreshing watermelon sweetness with a cooling ice finish, all at zero nicotine for universal appeal. These slim pouches deliver 20 consistent portions per can, each dissolving smoothly to release layers of fruity, icy flavour. Ideal for warm weather use, sports activities, or anyone seeking nicotine-free refreshment throughout their day. The watermelon provides natural sweetness whilst the ice element adds an invigorating coolness that lingers pleasantly. Perfect for social situations, work environments, or as a flavourful alternative to traditional beverages. The premium blend ensures every portion delivers genuine, recognisable watermelon character without artificial harshness.' WHERE id = 'f6e6f69a-fb95-4d5b-a9ab-660d1a0bca90';

-- Product: LEO Sour Peach Zero
UPDATE products SET description = 'LEO Sour Peach Zero delivers bright, tangy peach flavour with a mouth-puckering sour edge, entirely nicotine-free for maximum versatility. These slim portions dissolve smoothly, offering 20 servings per can of consistent fruity, tart satisfaction. The sour profile distinguishes this variety from standard peach blends, appealing to those who enjoy challenging, bold flavours alongside the ritual of pouches. Ideal for daytime use, social settings, or as a refreshing alternative to sugary drinks. Perfect for users exploring zero-nicotine options, younger demographics, or experienced users incorporating variety into their rotation. The premium sourcing ensures authentic peach character with genuine tartness rather than artificial sweetness.' WHERE id = '6284464a-a529-4509-9964-3badd768d25b';

-- Product: Kopia Bleck Cherry Zero
UPDATE products SET description = 'Kopia Black Cherry Zero (stylised as Bleck) delivers rich, dark cherry flavour with subtle depth at zero nicotine, perfect for those seeking mature taste profiles without nicotine. These slim pouches provide 20 portions per can, each dissolving gradually to release complex cherry notes that evolve throughout the duration. The darker cherry profile sets this apart from lighter berry varieties, appealing to experienced users and those who appreciate genuine fruit character. Ideal for all-day discretion, professional environments, or mixing with stronger varieties to create custom experiences. The premium blend balances sweetness with subtle tartness, creating sophistication without artificial notes.' WHERE id = '63a58ff0-5d57-4758-8010-b851fc4c6518';

-- Product: LEO Freeze Ice Zero
UPDATE products SET description = 'LEO Freeze Ice Zero delivers pure, frosty refreshment with zero nicotine, ideal for those craving the ultimate cooling sensation without stimulation. These slim pouches contain 20 portions per can, each providing strong, persistent ice-mint character that clears the palate and refreshes the mind. Perfect for warm weather, physical activity, or whenever you need mental clarity alongside flavour. The intense frost effect makes this standout for users seeking something beyond standard mint—it's a full-sensory ice experience. Ideal for all-day wear in professional or social settings, or for experienced users who appreciate extreme cooling profiles. The clean, crisp finish leaves no artificial aftertaste.' WHERE id = '302b54ed-f4ed-42a0-ad7a-37e17510299a';

-- Product: LEO Freeze Ice Max
UPDATE products SET description = 'LEO Freeze Ice Max brings extreme cooling and nicotine strength together at 16mg, delivering the ultimate experience for experienced users seeking intense refreshment and substantial nicotine delivery. These slim portions release their potency gradually, perfect for all-day satisfaction or strategic use during challenging moments. With 20 portions per can, the powerful ice-mint profile combined with extra-strong nicotine creates an invigorating, sensory-complete experience. Ideal for those transitioning from cigarettes, seeking maximum impact, or experienced users who appreciate bold, uncompromising products. The frosty intensity masks the nicotine strength, creating an unusually smooth sensation despite the high delivery.' WHERE id = '28cd813b-37b1-4449-8d0b-de94329c080c';

-- Product: LEO Dubai Chocolat Strong
UPDATE products SET description = 'LEO Dubai Chocolat Strong offers sophisticated chocolate blended with hints of caramel and exotic spice at 12mg strength, designed for those seeking dessert-inspired complexity. These slim portions dissolve gradually, delivering rich, rounded flavour profile that feels indulgent without being cloying. With 20 servings per can, this product suits connoisseurs who appreciate unconventional flavours in their daily routine. The 12mg strength provides robust nicotine delivery without excessive intensity, making it ideal for daytime use by experienced users. Perfect for post-meal satisfaction, creative professionals, or anyone seeking something distinctly different from standard mint or fruit varieties. The premium formula balances chocolate authenticity with subtle spice undertones.' WHERE id = '02d0f81f-dd0d-42f2-8605-e6034a2329e0';

-- Product: LEO Strawberry Kiwi Lime
UPDATE products SET description = 'LEO Strawberry Kiwi Lime delivers vibrant tropical fruit complexity at a potent 12mg strength, ideal for experienced users seeking adventurous flavour. These slim pouches combine three distinct fruity profiles—strawberry sweetness, kiwi tartness, and lime brightness—creating a refreshingly complex experience. With 20 portions per can, the gradual nicotine delivery pairs perfectly with the multi-layered taste profile. Perfect for those who've mastered lighter strengths and want to explore genuinely interesting flavour combinations alongside increased nicotine impact. The extra-strong formulation ensures sustained satisfaction throughout the day for demanding users. Ideal for daytime use by experienced consumers seeking something beyond standard varieties.' WHERE id = '1074230e-ce18-41f9-885f-7485e63fc374';

-- Product: LEO Black Cherry Strong
UPDATE products SET description = 'LEO Black Cherry Strong combines deep, authentic black cherry flavour with a substantial 12mg nicotine punch, crafted for experienced users seeking bold fruit character. These slim portions deliver 20 consistent servings per can, with the cherry profile perfectly complementing the extra-strong nicotine delivery. The darker cherry profile provides sophistication beyond typical bright berry varieties, appealing to discerning palates. Ideal for all-day professional use, commuting, or anyone who appreciates genuine fruit character alongside powerful nicotine satisfaction. The extra-strong formulation creates a complete sensory experience where flavour and strength reinforce each other. Perfect for those transitioning from snus or seeking maximum satisfaction in a slim pouch.' WHERE id = '790e3fec-69d2-431c-8c59-9340e90f6259';

-- Product: LEO Blue Razz Ice Strong
UPDATE products SET description = 'LEO Blue Razz Ice Strong combines the iconic tart berry flavour with cooling intensity and robust 12mg nicotine strength for maximum sensory impact. These slim pouches deliver 20 portions per can, perfect for experienced users seeking both flavour complexity and strong nicotine delivery. The blue razz profile provides playful tartness whilst the ice element adds refreshing cool sensations—ideal for warm weather or whenever you need an energising boost. The 12mg strength ensures all-day satisfaction even for demanding users. Perfect for daytime professional use, active pursuits, or anyone who appreciates bolder, more challenging flavour profiles alongside substantial nicotine impact. The premium formula delivers genuine candy-like character without artificial harshness.' WHERE id = 'd6f32acc-645f-4355-823e-7f19e708f65b';

-- Product: LEO Freeze Ice Strong
UPDATE products SET description = 'LEO Freeze Ice Strong delivers extreme cooling sensation paired with a formidable 12mg nicotine strength, designed for the most demanding users seeking intense refreshment. These slim portions provide 20 servings per can, each releasing powerful ice-mint character that completely dominates the palate. The frosty intensity is remarkable—clearing sinuses and sharpening mental focus whilst delivering robust nicotine satisfaction. Perfect for early mornings, physical activity, professional stress, or anyone who appreciates extreme cooling profiles. The strong nicotine content ensures all-day performance for experienced users, whilst the intense flavour profile masks strength for an unusually smooth sensation. Ideal for those transitioning from powerful tobacco products or seeking maximum sensory impact.' WHERE id = 'ce977311-039c-405d-a48e-e5f0603a90f7';

-- Product: LEO Watermelon Ice Strong
UPDATE products SET description = 'LEO Watermelon Ice Strong captures juicy watermelon freshness with an invigorating ice cooling effect, backed by substantial 12mg nicotine for complete satisfaction. These slim pouches contain 20 portions per can, ideal for experienced users seeking balanced fruit and cool sensations alongside strong nicotine delivery. The watermelon provides natural sweetness whilst the ice element creates refreshing contrast—perfect for warm weather or whenever you need an energising pick-me-up. The 12mg strength ensures sustained all-day satisfaction for demanding users. Perfect for daytime professional use, active individuals, or anyone who appreciates both flavour complexity and nicotine power. The premium formula delivers authentic watermelon character with genuine cooling impact.' WHERE id = '581603b0-8993-475e-ba27-3698402046ba';

-- Product: LEO Sour Peach Strong
UPDATE products SET description = 'LEO Sour Peach Strong combines bright, tangy peach with tart sensation and a commanding 12mg nicotine delivery for experienced users seeking bold impact. These slim portions provide 20 consistent servings per can, perfect for those who appreciate challenging, distinctive flavours alongside strong nicotine satisfaction. The sour profile distinguishes this from standard fruit varieties—providing mouth-puckering character that keeps your palate engaged throughout each portion. The 12mg strength ensures all-day performance for demanding users. Perfect for daytime professional use, active pursuits, or anyone seeking something genuinely different from typical mint-dominated offerings. The authentic peach character balances tartness beautifully, creating a memorable sensory experience without artificial notes.' WHERE id = '037f1b26-27bf-400e-8b68-3f429cad95a0';

-- Product: CUBA Blackberry
UPDATE products SET description = 'CUBA Blackberry delivers intense, dark berry character backed by an extreme 43mg nicotine strength—exclusively for experienced users seeking maximum impact. These slim pouches pack serious intensity into a compact format, providing profound nicotine delivery and rich, fruity satisfaction simultaneously. The blackberry flavour is sophisticated and deep, complementing rather than competing with the ultra-strong nicotine content. Perfect for all-day wear by experienced users, those transitioning from heavy tobacco use, or anyone seeking the most powerful nicotine solution available. The 20 portions per can ensure reliable daily supply for demanding consumption patterns. Not recommended for new users or those seeking moderate nicotine intake. Requires experience and tolerance to enjoy safely.' WHERE id = 'b364cdce-c997-419b-934a-7c7ff86a2a4c';

-- Product: ZYN Peppermint Slim S3
UPDATE products SET description = 'ZYN Peppermint Slim S3 delivers crisp, authentic peppermint at 9mg strength—ideal for users seeking strong nicotine with iconic ZYN quality. These slim pouches provide 20 consistent portions per can, with the classic peppermint profile that has defined the category for generations. The 9mg strength targets experienced users seeking substantial nicotine without extreme intensity, perfect for all-day professional wear or active pursuits. ZYN's premium formulation ensures smooth, satisfying release with minimal irritation. The slim format delivers maximum discretion whilst the distinctive peppermint flavour provides reliable, tried-and-tested satisfaction. Perfect for those who know what they like and want consistent, premium delivery without experimentation. A proven choice for experienced users worldwide.' WHERE id = '50fe438f-c3da-458c-8509-40817aa9f2c3';

-- Product: ZYN Black Cherry Slim S3
UPDATE products SET description = 'ZYN Black Cherry Slim S3 combines sophisticated dark cherry flavour with the trusted 9mg strength ZYN is known for, designed for experienced users seeking fruit-forward nicotine pouches. These slim portions deliver 20 consistent servings per can, with the deeper cherry profile providing genuine fruit character rather than artificial sweetness. The 9mg strength positions this as a strong offering for all-day use by established users. ZYN's premium formulation ensures smooth, sustained release with ZYN's characteristic quality and refinement. Perfect for those who appreciate ZYN's reputation for consistency and want to explore beyond peppermint whilst maintaining the strength they're accustomed to. The darker berry profile suits more sophisticated palates.' WHERE id = '5b6df1ca-1bc1-4fd1-aee7-12d25fd63dd4';

-- Product: Fix Spearmint S3
UPDATE products SET description = 'Fix Spearmint S3 delivers bright, herbaceous spearmint at a measured 8.4mg strength, perfect for users seeking strong nicotine with distinctive mint character. These slim pouches contain 20 portions per can, with spearmint providing a cleaner, less peppery profile than traditional mint varieties. The 8.4mg strength targets experienced users seeking substantial nicotine delivery without extreme intensity, ideal for all-day professional wear or active use. Fix's premium formulation ensures consistent, smooth release throughout each pouch's duration. The distinctive spearmint character sets this apart from peppermint-dominated options, appealing to those who appreciate herbal nuance alongside strong nicotine. Perfect for experienced users exploring different mint profiles whilst maintaining significant strength.' WHERE id = 'b17d209b-0f9a-43ca-9b7d-bfdd8a70e5ac';

-- Product: Fix Peppermint S4
UPDATE products SET description = 'Fix Peppermint S4 combines classic peppermint with a robust 9.8mg nicotine strength, delivering strong satisfaction for experienced users seeking premium quality. These slim portions provide 20 consistent servings per can, with the iconic peppermint profile delivering familiar, reliable pleasure. The 9.8mg strength ensures substantial all-day performance for demanding users. Fix's premium formulation provides smooth, consistent release without harsh irritation, appealing to those who value quality and predictability. The peppermint character is crisp and authentic, never artificial or cloying. Perfect for experienced users who've built tolerance and seek robust nicotine delivery within a premium, trusted product. Ideal for professional or social settings requiring reliable, discreet satisfaction.' WHERE id = 'd90cf8df-42d5-44eb-ac69-38066764f6df';

-- Product: Après Mochaccino
UPDATE products SET description = 'Après Mochaccino delivers luxurious coffee and chocolate blended experience at a measured 4mg strength, ideal for users seeking sophisticated, dessert-inspired relaxation. These slim pouches contain 20 portions per can, perfect for afternoon use or whenever you want indulgence without heavy nicotine impact. The mochaccino profile captures rich espresso with smooth chocolate undertones, creating a genuinely premium sensory experience. The 4mg strength suits those seeking gentle nicotine alongside distinctive, memorable flavour—perfect for new users or experienced consumers wanting flavour-focused rather than nicotine-focused satisfaction. Ideal for workplace breaks, social situations, or post-meal moments when you want something special. Après's premium positioning and meticulous craftsmanship ensure every pouch delivers genuine coffee-and-chocolate character.' WHERE id = '639864b0-b666-4f9b-b621-6422085dd692';

-- Product: Après Raspberry Liqorice Hyper Strong
UPDATE products SET description = 'Après Raspberry Liquorice Hyper Strong combines tart raspberry with distinctive liquorice notes at a commanding 11mg strength, designed for adventurous, experienced users. These slim pouches deliver 20 portions per can, creating an unusually complex flavour experience that challenges and rewards sophisticated palates. The raspberry provides bright tartness whilst liquorice adds anise-like depth—a genuinely distinctive combination rarely seen in the market. The 11mg strength ensures robust nicotine satisfaction alongside the complex flavour profile. Perfect for experienced users seeking something genuinely different, flavour enthusiasts, or those who appreciate challenging tastes. Ideal for daytime professional use, active pursuits, or anyone willing to explore beyond conventional varieties. Après's meticulous approach ensures the unconventional flavour combination works beautifully.' WHERE id = '7188bb01-77d3-4b8e-875d-4a7cfe61d34c';

-- Product: Après Mochaccino Hyper Strong
UPDATE products SET description = 'Après Mochaccino Hyper Strong elevates the original mochaccino experience with a substantial 11mg nicotine strength, perfect for users seeking sophisticated dessert flavours with serious nicotine impact. These slim pouches deliver 20 portions per can, combining rich coffee-and-chocolate character with robust satisfaction for all-day use by experienced consumers. The espresso provides deep complexity whilst premium chocolate adds smoothness—creating a genuinely luxurious sensory experience. The 11mg strength ensures sustained performance for demanding users seeking robust nicotine alongside distinctive flavour. Perfect for experienced users who appreciate Après's quality and want to maintain stronger nicotine intake without sacrificing sophistication. Ideal for professional or creative settings where flavour complexity enhances focus. A premium choice for those who've outgrown lower strengths but still value genuine taste.' WHERE id = '50edf984-94e9-49a4-9416-bdf49ef63ec9';

-- Product: Kyletiketter KLAR
UPDATE products SET description = 'KLAR (Kyletiketter) delivers pure, clean mint experience at zero nicotine, designed for those seeking the ritual and refreshment without any nicotine content. These slim pouches provide 20 portions per can, each dissolving to release crisp, authentic mint character. The zero-nicotine formulation makes KLAR ideal for nicotine-free lifestyles, younger users, social situations where alternatives are valued, or experienced users incorporating variety into their rotation. The premium flavour ensures genuine satisfaction without nicotine dependence. Perfect for all-day discretion, professional environments, or mixing with stronger varieties to moderate overall intake. KLAR's reputation for quality Swedish craftsmanship ensures every pouch delivers consistent, recognisable mint pleasure. An excellent choice for those prioritising flavour and ritual over nicotine delivery.' WHERE id = '0628cd7c-552d-492b-b4d3-0c3e954cfada';

-- Product: VELO Tomorrowland Limited Edition
UPDATE products SET description = 'VELO Tomorrowland Limited Edition captures festival spirit with a vibrant, modern fruity flavour at 8mg strength, designed for users seeking contemporary appeal and strong satisfaction. These slim pouches deliver 20 portions per can, combining energetic fruit notes with the reliable nicotine performance VELO is renowned for. The 8mg strength targets experienced users seeking substantial nicotine without extreme intensity, perfect for all-day professional wear or active pursuits. This limited-edition release celebrates VELO's innovation in flavour development, offering something genuinely contemporary alongside proven nicotine delivery. Perfect for users who appreciate cutting-edge product development and want to experience exclusive, time-limited offerings. The vibrant fruity character reflects the forward-thinking spirit of Tomorrowland festival. Ideal for experienced users seeking something special and memorable within VELO's trusted quality framework.' WHERE id = 'f89bcfdf-9db8-4963-803b-2920e75ee28b';

-- Product: Kelly White Hot Cherry Slim Strong
UPDATE products SET description = 'Kelly White Hot Cherry Slim Strong delivers bold cherry flavour with spicy heat undertones at 8mg strength, perfect for users seeking adventurous, warming sensations. These slim pouches contain 20 portions per can, combining genuine cherry character with distinctive spicy warming that builds throughout each pouch's duration. The 8mg strength provides substantial nicotine satisfaction for experienced users seeking all-day performance. The "hot" element distinguishes this from standard cherry varieties—creating tingling warmth that energises and invigorates. Perfect for cool weather, active pursuits, or anyone seeking distinctive sensory experiences beyond conventional sweet-or-cooling options. Kelly White's heritage ensures quality formulation where the spicy warmth complements rather than overwhelms the cherry foundation. Ideal for adventurous, experienced users wanting something genuinely different.' WHERE id = '9fc4335a-e502-4af2-9f4e-bdc80576cce9';

-- Product: VELO Bright Spearmint 14mg
UPDATE products SET description = 'VELO Bright Spearmint 14mg delivers classic spearmint character with commanding 14mg nicotine strength, designed for experienced users seeking maximum performance and iconic flavour. These slim pouches provide 20 consistent portions per can, with the bright spearmint profile perfectly complementing the extra-strong nicotine delivery. The 14mg strength targets demanding users seeking robust all-day satisfaction, particularly those transitioning from cigarettes or heavier tobacco products. VELO's premium formulation ensures smooth, consistent release despite the high nicotine content. The distinctive spearmint—brighter and less peppery than alternatives—provides the familiar character VELO users expect. Perfect for experienced consumers demanding maximum nicotine within a proven, trusted product. Ideal for all-day professional wear where discretion meets substantial performance. Not recommended for new users.' WHERE id = 'ce90449b-b5a2-4469-8e07-c2131b1d2213';

-- Product: JUICE HEAD Watermelon Strawberry Ultra Strong
UPDATE products SET description = 'JUICE HEAD Watermelon Strawberry Ultra Strong combines two beloved fruit flavours with an extreme 20mg nicotine punch, exclusively for experienced users seeking maximum impact. These slim pouches deliver 20 portions per can, with the fresh, juicy watermelon-strawberry blend providing genuine fruity character alongside the ultra-strong nicotine delivery. The watermelon provides crisp refreshment whilst strawberry adds bright sweetness—creating a genuinely appealing taste experience. The 20mg strength ensures all-day sustained satisfaction for the most demanding users. Perfect for experienced consumers, those transitioning from heavy tobacco, or anyone seeking the most powerful nicotine solution with genuine flavour appeal. The premium fruit blend never feels artificial despite the extreme strength. A bold choice for those with serious nicotine requirements seeking reliable daily performance.' WHERE id = '1a4c1201-52fe-4e3d-91e5-5071cdce921d';

-- Product: JUICE HEAD Watermelon Strawberry Super Strong
UPDATE products SET description = 'JUICE HEAD Watermelon Strawberry Super Strong delivers the beloved fruit duo at a substantial 14mg strength, perfect for experienced users seeking robust nicotine with genuine fruity appeal. These slim pouches provide 20 portions per can, combining the crisp refreshment of watermelon with bright strawberry sweetness. The 14mg strength ensures all-day performance for demanding users without reaching extreme intensity. The two-fruit blend provides complexity that prevents flavour fatigue—keeping each pouch enjoyable throughout its duration. Perfect for those transitioning from lighter strengths, seeking all-day professional reliability, or wanting robust nicotine within a genuinely tasty format. JUICE HEAD's fruit-forward approach appeals to users who've moved beyond mint-dominated products. Ideal for active pursuits, commuting, or sustained daytime wear.' WHERE id = '712c9338-88ff-4c90-ad51-e7f9ed812e2d';

-- Product: JUICE HEAD Watermelon Strawberry Strong
UPDATE products SET description = 'JUICE HEAD Watermelon Strawberry Strong pairs the iconic fruit combination with 9mg nicotine strength, ideal for users seeking balanced flavour and solid performance. These slim pouches deliver 20 consistent portions per can, with watermelon providing crisp juiciness and strawberry adding complementary sweetness. The 9mg strength targets experienced users seeking substantial nicotine delivery during all-day wear or active pursuits. The fruit-forward approach appeals to those who've outgrown beginner strengths but appreciate genuine taste alongside nicotine performance. Perfect for professional environments where discretion matters, social situations, or anyone seeking reliable, tasty daily satisfaction. The two-fruit complexity ensures interesting flavour throughout each pouch's duration. Ideal for experienced users exploring JUICE HEAD's fruit-focused portfolio without maximum intensity.' WHERE id = '75d6525b-9b44-4667-b86c-1e87e69afd37';

-- Product: JUICE HEAD Watermelon Strawberry Regular
UPDATE products SET description = 'JUICE HEAD Watermelon Strawberry Regular introduces the popular fruit combination at an accessible 6mg strength, perfect for users building nicotine tolerance or seeking balanced, flavour-focused experience. These slim pouches contain 20 portions per can, delivering the refreshing blend of crisp watermelon and bright strawberry. The 6mg strength suits experienced users seeking moderate nicotine alongside genuine fruity satisfaction, or newer consumers exploring fruit varieties without overwhelming nicotine impact. The two-fruit approach provides enough complexity to keep each pouch interesting throughout its duration. Perfect for daytime professional use, social situations, or anyone prioritising flavour character alongside steady, predictable nicotine delivery. JUICE HEAD's reputation for quality fruit formulations ensures authentic taste without artificial notes. An excellent entry point into stronger fruit-forward pouches.' WHERE id = '4b99d2e2-9cf6-4f41-835b-94da072a5db4';

-- Product: JUICE HEAD Spicy Pineapple Ultra Strong
UPDATE products SET description = 'JUICE HEAD Spicy Pineapple Ultra Strong combines tropical pineapple with warming spice at an extreme 20mg strength, designed exclusively for experienced users seeking maximum sensory impact. These slim pouches deliver 20 portions per can, with the bright pineapple providing juicy tropical character whilst subtle spice adds warmth and complexity. The pineapple sweetness balances the spice beautifully—creating a memorable, genuinely distinctive experience. The 20mg strength ensures sustained all-day satisfaction for the most demanding users or those transitioning from heavy tobacco products. Perfect for those seeking something genuinely different from conventional varieties, the ultimate in nicotine delivery, or flavour adventurers willing to explore unconventional combinations. The premium formula ensures the spiced tropical profile works beautifully despite extreme strength. A bold, unforgettable choice.' WHERE id = '9dcbaa53-bbc6-4ccc-8284-b9bba1e6f940';

-- Product: JUICE HEAD Spicy Pineapple Super Strong
UPDATE products SET description = 'JUICE HEAD Spicy Pineapple Super Strong delivers tropical fruit with warming spice at a commanding 14mg strength, perfect for experienced users seeking distinctive flavour alongside robust nicotine. These slim pouches provide 20 portions per can, combining bright pineapple character with subtle warmth that builds throughout each pouch's duration. The 14mg strength ensures all-day performance for demanding users without extreme intensity. The spiced pineapple combination is genuinely unique—providing both sweet tropical appeal and warming complexity. Perfect for users transitioning from lighter strengths, seeking all-day professional reliability, or wanting something genuinely different from standard mint offerings. JUICE HEAD's meticulous flavour development ensures the unconventional spice-and-pineapple pairing works beautifully. Ideal for adventurous, experienced users.' WHERE id = 'e4c7b8fb-bd9d-4dd8-bc37-51b7e25c85b3';

-- Product: JUICE HEAD Spicy Pineapple Strong
UPDATE products SET description = 'JUICE HEAD Spicy Pineapple Strong brings tropical island vibes with warming spice at 9mg strength, designed for users seeking distinctive flavour alongside solid nicotine delivery. These slim pouches deliver 20 portions per can, with bright pineapple providing genuine tropical character whilst subtle spice creates warming, lingering sensations. The 9mg strength targets experienced users seeking substantial nicotine without extreme intensity, perfect for all-day professional wear or active pursuits. The unique spice-and-pineapple pairing stands out—appealing to adventurous palates tired of conventional mint or fruit-only options. Perfect for those wanting something genuinely different, exploring JUICE HEAD's innovative flavours, or seeking reliable daily satisfaction with memorable taste. The tropical-meets-spicy profile suits warm weather and year-round enjoyment. An excellent choice for flavour-forward, experienced users.' WHERE id = '796808f3-7182-4d30-9f41-278d9135c783';

-- Product: JUICE HEAD Spicy Pineapple Regular
UPDATE products SET description = 'JUICE HEAD Spicy Pineapple Regular offers the distinctive spiced-pineapple experience at an accessible 6mg strength, perfect for users exploring innovative flavours or building nicotine tolerance. These slim pouches contain 20 portions per can, delivering bright tropical character with subtle warming spice that adds memorable complexity. The 6mg strength suits experienced users seeking moderate nicotine alongside adventurous flavour, or newer consumers exploring beyond standard offerings. The unconventional spice-and-pineapple combination is approachable yet distinctive—keeping each pouch engaging without overwhelming. Perfect for daytime professional use, social situations, or anyone willing to venture beyond traditional options. JUICE HEAD's flavour expertise ensures the spiced tropical profile delivers genuine pleasure. An excellent entry point for those curious about more complex, memorable flavour experiences.' WHERE id = '8c2f0f86-0f58-4ffb-935b-d4a58d775ff5';

-- Product: JUICE HEAD Peach Pineapple Ultra Strong
UPDATE products SET description = 'JUICE HEAD Peach Pineapple Ultra Strong combines warm peach with tropical pineapple at an extreme 20mg strength, exclusively for experienced users seeking maximum nicotine impact with genuinely appealing flavour. These slim pouches deliver 20 portions per can, with the peach-pineapple blend providing warm stone-fruit sweetness alongside bright tropical character. The flavour complexity ensures engaging sensory experience throughout each pouch's duration, never becoming monotonous. The 20mg strength ensures sustained all-day satisfaction for demanding users or those transitioning from heavy tobacco products. Perfect for those seeking something genuinely delicious alongside extreme nicotine delivery, or experienced users wanting maximum performance with premium flavour. The dual-fruit approach appeals to those who've moved beyond single-flavour products. A sophisticated, high-impact choice for experienced consumers.' WHERE id = 'dbf5e862-76a6-41f2-b0fb-700fd672700a';

-- Product: JUICE HEAD Peach Pineapple Super Strong
UPDATE products SET description = 'JUICE HEAD Peach Pineapple Super Strong pairs warm stone-fruit peach with bright tropical pineapple at 14mg strength, designed for experienced users seeking flavourful complexity alongside robust nicotine. These slim pouches provide 20 portions per can, with the peach providing warm sweetness and pineapple adding tropical brightness. The two-fruit combination creates genuine complexity that sustains interest throughout each pouch's duration. The 14mg strength ensures all-day performance for demanding users without reaching extreme intensity. Perfect for those transitioning from lighter strengths, wanting something genuinely flavourful and memorable, or seeking reliable daily satisfaction with premium character. JUICE HEAD's meticulous flavour development ensures the peach-pineapple pairing delivers authentic, well-balanced pleasure. Ideal for adventurous, experienced users wanting dual-fruit complexity.' WHERE id = 'e6023d66-1de9-4f5e-80f6-81b8ea16ff31';

-- Product: JUICE HEAD Peach Pineapple Strong
UPDATE products SET description = 'JUICE HEAD Peach Pineapple Strong delivers the appealing peach-pineapple duo at 9mg strength, perfect for users seeking genuine fruit complexity alongside solid all-day nicotine. These slim pouches contain 20 portions per can, with warm peach sweetness beautifully complementing tropical pineapple brightness. The 9mg strength targets experienced users seeking substantial nicotine delivery during professional wear, active pursuits, or extended daily use. The dual-fruit approach provides enough flavour complexity to prevent fatigue—each pouch remains engaging. Perfect for those appreciating genuine fruit character over mint-dominated options, wanting reliable daily satisfaction, or exploring JUICE HEAD's diverse portfolio. The peach-pineapple pairing suits warm weather and year-round enjoyment. Ideal for experienced users seeking memorable, balanced flavour-and-nicotine synergy.' WHERE id = '20935e87-f223-4b68-a768-572869ea3b21';

-- Product: JUICE HEAD Peach Pineapple Regular
UPDATE products SET description = 'JUICE HEAD Peach Pineapple Regular introduces the pleasant peach-pineapple blend at an accessible 6mg strength, ideal for users exploring dual-fruit complexity or building nicotine tolerance. These slim pouches deliver 20 portions per can, with warm peach providing stone-fruit sweetness and bright pineapple adding tropical character. The 6mg strength suits experienced users seeking moderate nicotine with adventurous flavour, or newer consumers exploring fruit varieties without overwhelming nicotine impact. The two-fruit approach provides genuine complexity whilst remaining approachable and accessible. Perfect for daytime professional use, social situations, or anyone seeking reliable, tasty satisfaction. JUICE HEAD's commitment to authentic flavours ensures genuine peach-pineapple pleasure without artificial notes. An excellent entry point into more sophisticated, multi-fruit offerings for those ready to explore beyond basics.' WHERE id = '51f66cc2-cbf2-4a35-920c-11d64a5e20c8';

-- Product: JUICE HEAD Blueberry Lemon Ultra Strong
UPDATE products SET description = 'JUICE HEAD Blueberry Lemon Ultra Strong combines tart blueberry with bright lemon at an extreme 20mg strength, designed exclusively for experienced users seeking maximum impact with genuinely memorable flavour. These slim pouches deliver 20 portions per can, with the blueberry providing depth and lemon adding sparkling brightness and tartness. The citrus-berry combination creates complex, engaging sensory experience throughout each pouch's duration. The 20mg strength ensures sustained all-day satisfaction for the most demanding users or those transitioning from heavy tobacco. Perfect for those seeking powerful nicotine delivery paired with authentic, sophisticated fruit character, or flavour adventurers willing to explore genuinely distinctive combinations. The tart profile balances beautifully with the robust nicotine—creating memorable, complete experience. A bold choice for experienced, adventurous consumers.' WHERE id = '06d1fea1-cf56-4947-a7cc-533fa437b619';

-- Product: JUICE HEAD Blueberry Lemon Super Strong
UPDATE products SET description = 'JUICE HEAD Blueberry Lemon Super Strong pairs tart berry with zesty citrus at a commanding 14mg strength, perfect for experienced users seeking distinctive flavour alongside robust nicotine delivery. These slim pouches contain 20 portions per can, with blueberry depth beautifully complemented by lemon brightness and natural tartness. The berry-citrus combination provides genuine complexity—keeping each pouch engaging without flavour fatigue. The 14mg strength ensures all-day performance for demanding users without extreme intensity. Perfect for those transitioning from lighter strengths, wanting something genuinely different from standard offerings, or seeking reliable daily satisfaction with premium flavour character. JUICE HEAD's meticulous flavour expertise ensures the blueberry-lemon pairing delivers authentic, well-balanced pleasure. Ideal for adventurous, experienced users appreciating citrus-berry synergy.' WHERE id = '1001c09e-dc06-42e2-a8cd-149d59a52533';

-- Product: JUICE HEAD Blueberry Lemon Strong
UPDATE products SET description = 'JUICE HEAD Blueberry Lemon Strong delivers the appealing berry-citrus combination at 9mg strength, designed for users seeking distinctive flavour alongside solid all-day nicotine performance. These slim pouches provide 20 portions per can, with tart blueberry providing depth and bright lemon adding sparkling freshness and natural tartness. The 9mg strength targets experienced users seeking substantial nicotine without extreme intensity, perfect for professional environments, active pursuits, or extended daily satisfaction. The citrus-berry complexity provides genuine interest—each pouch remains engaging throughout its duration. Perfect for those appreciating distinctive fruit combinations, wanting genuine flavour character over conventional options, or exploring JUICE HEAD's innovative portfolio. The tart profile appeals to sophisticated palates. Ideal for experienced users seeking memorable, balanced flavour-and-nicotine satisfaction.' WHERE id = '20f754da-61f4-42c8-aca4-01898f211ec9';

-- Product: JUICE HEAD Blueberry Lemon Regular
UPDATE products SET description = 'JUICE HEAD Blueberry Lemon Regular introduces the distinctive berry-citrus blend at an accessible 6mg strength, perfect for users exploring complex flavours or building nicotine tolerance. These slim pouches deliver 20 portions per can, with tart blueberry providing depth and bright lemon adding sparkling character. The 6mg strength suits experienced users seeking moderate nicotine with adventurous flavour, or newer consumers exploring fruit varieties without overwhelming impact. The citrus-berry combination is genuinely distinctive—providing complexity whilst remaining approachable and accessible. Perfect for daytime professional use, social situations, or anyone willing to explore beyond conventional single-flavour products. JUICE HEAD's commitment to authentic flavours ensures genuine blueberry-lemon pleasure. An excellent entry point into more sophisticated, multi-fruit combinations for those ready to discover distinctive taste experiences.' WHERE id = '848f9780-d1a9-4fb0-bc6b-305867ddfe93';

-- Product: JUICE HEAD Arctic Mint Ultra Strong
UPDATE products SET description = 'JUICE HEAD Arctic Mint Ultra Strong delivers intense, frosty cooling at an extreme 20mg nicotine strength, exclusively for experienced users seeking maximum sensory impact and performance. These slim pouches provide 20 portions per can, with the arctic cooling effect creating profound refreshment that clears sinuses and sharpens mental focus. The intense frost sensation dominates the palate—unusual among ultra-strong products where strength often overwhelms flavour. The 20mg strength ensures sustained all-day satisfaction for the most demanding users or those transitioning from heavy tobacco products. Perfect for early mornings, physical activity, mental clarity moments, or anyone seeking the ultimate cooling experience combined with maximum nicotine. The premium formulation ensures the extreme frost effect works beautifully despite powerful nicotine delivery. A bold, energising choice for experienced, demanding users.' WHERE id = '5344a6e9-995e-43b0-b891-31911c6e3912';

-- Product: JUICE HEAD Arctic Mint Super Strong
UPDATE products SET description = 'JUICE HEAD Arctic Mint Super Strong combines extreme cooling sensation with a substantial 14mg nicotine strength, designed for experienced users seeking intense refreshment and robust performance. These slim pouches deliver 20 portions per can, with the arctic frost effect creating profound sensory impact—clearing mental fog and sharpening focus. The 14mg strength ensures all-day satisfaction for demanding users without reaching extreme intensity. The intense cooling is remarkable—persisting throughout each pouch's duration, making this standout among strong-strength offerings. Perfect for early mornings, demanding work, physical activity, or anyone seeking maximum refreshment and nicotine synergy. The premium formulation ensures the intense mint character remains distinctive despite robust nicotine delivery. Ideal for experienced users prioritising intense cooling alongside substantial performance.' WHERE id = '93d38fd6-3890-4dc8-b5cb-2aa907df99ad';

-- Product: JUICE HEAD Arctic Mint Strong
UPDATE products SET description = 'JUICE HEAD Arctic Mint Strong delivers remarkable frosty cooling paired with 9mg nicotine strength, perfect for users seeking intense refreshment and solid all-day performance. These slim pouches contain 20 portions per can, with the arctic sensation creating genuine mental clarity and palate refreshment. The 9mg strength targets experienced users seeking substantial nicotine delivery during professional wear, active pursuits, or extended daily use. The cooling intensity is distinctive—setting this apart from standard mint offerings by providing a genuinely powerful, sensory-complete experience. Perfect for early mornings, demanding work environments, physical activity, or anyone wanting substantial nicotine alongside remarkable refreshment. JUICE HEAD's premium formulation ensures the intense cooling character remains present throughout each pouch's duration. Ideal for experienced users prioritising genuine sensory impact alongside reliable performance.' WHERE id = 'ded7073a-49a9-457c-aa01-892e8d161fb9';

-- Product: JUICE HEAD Arctic Mint Regular
UPDATE products SET description = 'JUICE HEAD Arctic Mint Regular introduces the distinctive arctic cooling at an accessible 6mg strength, perfect for users exploring intense mint experiences or building nicotine tolerance. These slim pouches deliver 20 portions per can, with remarkable frosty character that creates genuine mental clarity and refreshment. The 6mg strength suits experienced users seeking moderate nicotine with adventurous sensory experience, or newer consumers exploring stronger flavours without overwhelming nicotine impact. The arctic cooling is genuinely distinctive—providing memorable sensory experience beyond conventional mint offerings. Perfect for daytime professional use, active pursuits, or anyone willing to explore beyond standard mint varieties. JUICE HEAD's commitment to authentic, intense flavours ensures genuine arctic mint pleasure. An excellent entry point for those curious about powerful cooling sensations combined with moderate nicotine strength.' WHERE id = 'dd580504-d7c7-44f0-be47-674274ca0e6b';

-- Product: Display Floating Can
UPDATE products SET description = 'Display Floating Can is a premium merchandising piece designed for retail environments, showcasing product quality and brand presence. This eye-catching display item features innovative floating can design that captures customer attention and elevates shelf presence. Perfect for retailers wanting distinctive visual merchandising that communicates premium brand positioning. The high-quality construction ensures durability through repeated handling and seasonal rotations. Ideal for highlighting new arrivals, seasonal collections, or brand-wide promotions. This display enhances customer experience by creating memorable product presentation that encourages engagement and purchase consideration. The sleek design complements modern retail aesthetics whilst maintaining practical functionality for product visibility and sales support.' WHERE id = '5b338939-81cf-49bf-81cb-465b0215b279';

-- Product: VELO Dark Cherry Mini
UPDATE products SET description = 'VELO Dark Cherry Mini delivers sophisticated dark cherry character at a measured 4mg strength, perfect for users seeking refined flavour in a compact mini format. These mini pouches provide 20 portions per can, with the deeper cherry profile providing genuine fruit character rather than artificial sweetness. The 4mg strength suits those seeking gentle nicotine alongside distinctive flavour—ideal for lighter use, flavour-focused experiences, or newer users exploring VELO's portfolio. The mini format offers different sensory properties—faster nicotine delivery and more concentrated flavour—appealing to those who prefer this approach. Perfect for daytime professional use, social situations, or anyone appreciating sophisticated fruit character without heavy nicotine demand. VELO's premium positioning ensures authentic cherry pleasure. An excellent choice for quality-conscious users seeking refinement and distinctive taste.' WHERE id = 'dd2dd7fc-55de-4071-a08f-72b2c8967075';

-- Product: MYNT Mango Slim Sample Bag
UPDATE products SET description = 'MYNT Mango Slim Sample Bag introduces MYNT's tropical mango at 12mg strength in a convenient, trial-friendly format with just 4 portions. Perfect for sampling before committing to full-size purchase, exploring this innovative brand, or gift-giving. The 12mg strength provides substantial nicotine for experienced users in ultra-compact packaging. The mango flavour delivers bright tropical character with genuine fruit appeal. The slim format offers maximum discretion whilst the sample-size minimises commitment—ideal for those exploring new brands, strengths, or flavours. Perfect for curious consumers, travellers, or anyone wanting to evaluate MYNT's quality and approach before larger investment. The convenient portability makes it ideal for trial periods or switching testing. MYNT's innovation is well-represented in this accessible sample format.' WHERE id = 'e8b991ba-b31e-42c9-b758-972af28cae6d';

-- Product: MYNT Mint Slim Sample Bag
UPDATE products SET description = 'MYNT Mint Slim Sample Bag showcases MYNT's signature mint at 12mg strength in a compact, trial-friendly 4-portion format. Perfect for sampling before larger purchase, exploring MYNT's distinctive approach, or gift-giving to curious users. The 12mg strength delivers substantial nicotine for experienced users within ultra-compact, portable packaging. The mint profile captures MYNT's innovative sensibility—providing distinctive character beyond conventional mint offerings. The slim sample format allows minimal commitment whilst delivering full MYNT experience. Perfect for curious consumers, travellers, or anyone wanting to evaluate MYNT quality before committing to standard cans. The convenient portability suits trial periods or brand-switching tests. An excellent introduction to MYNT's philosophy and products. Ideal for exploring new brands and styles without significant investment.' WHERE id = '673ab181-c64d-4fa7-ba4e-b034f4709593';

-- Product: MYNT Spearmint Slim Sample Bag
UPDATE products SET description = 'MYNT Spearmint Slim Sample Bag presents MYNT's distinctive spearmint at 12mg strength in a convenient 4-portion sample format. Perfect for trial before committing to full-size, exploring MYNT's brand identity, or introducing curious friends. The 12mg strength provides substantial nicotine for experienced users in ultra-portable packaging. The spearmint profile—brighter and less peppery than traditional peppermint—showcases MYNT's attention to flavour nuance. The slim sample format allows exploration with minimal commitment. Perfect for curious consumers wanting to evaluate MYNT quality and approach before larger investment, or travellers seeking convenient, discreet performance. The compact size suits trial periods, brand exploration, or testing switching compatibility. An excellent introduction to MYNT's innovation. Ideal for those wanting authentic spearmint character within accessible, low-commitment packaging.' WHERE id = 'e88078a0-ca5a-467f-a5a5-b5da43fc1aad';

-- Product: MYNT Winter Green Sample Bag
UPDATE products SET description = 'MYNT Winter Green Sample Bag features MYNT's rich, herbaceous winter green at 12mg strength in a convenient 4-portion trial format. Perfect for sampling distinctive flavour before full-size commitment, exploring MYNT innovation, or gift-giving. The 12mg strength delivers substantial nicotine for experienced users within ultra-compact, portable packaging. Winter green provides complex herbaceous character that distinguishes this from conventional mint varieties—capturing authentic leaf notes and natural coolness. The slim sample format enables full MYNT experience with minimal commitment. Perfect for curious consumers, flavour adventurers, or anyone wanting to evaluate MYNT quality before larger investment. The convenient portability suits travel, trial periods, or brand-exploration testing. An excellent introduction to MYNT's distinctive approach. Ideal for those seeking something genuinely different from mainstream options.' WHERE id = 'd83778ed-b974-4e7c-b20d-0e6490e68512';

-- Product: GLICK Pink Fusion Extreme Sample Bag
UPDATE products SET description = 'GLICK Pink Fusion Extreme Sample Bag introduces GLICK's innovative pink fusion at 10mg strength in a compact 5-portion sample format. Perfect for trial before commitment, exploring GLICK's distinctive approach, or gift-giving. The 10mg strength provides solid nicotine performance for experienced users within ultra-portable packaging. Pink Fusion represents GLICK's creative approach—blending unexpected flavours into genuinely distinctive experience. The sample format allows full GLICK exploration with minimal commitment. Perfect for curious consumers, flavour adventurers, or anyone wanting to evaluate GLICK quality and innovation before larger investment. The convenient, discreet portability suits travel and brand exploration. The "Extreme" designation hints at GLICK's bold approach. Ideal for those seeking genuinely different products beyond mainstream offerings. An excellent introduction to GLICK's creative philosophy.' WHERE id = 'e8c72d5b-6aaa-408e-8f15-aafe3e7d10a1';

-- Product: GLICK Ice Mint Extreme Sample Bag
UPDATE products SET description = 'GLICK Ice Mint Extreme Sample Bag presents GLICK's powerful ice-mint at 10mg strength in a convenient 5-portion trial format. Perfect for sampling distinctive cooling before full-size commitment, exploring GLICK innovation, or introducing curious users. The 10mg strength delivers solid nicotine performance for experienced users within ultra-compact, portable packaging. Ice Mint captures GLICK's bold approach—providing extreme cooling sensation paired with robust nicotine delivery. The slim sample format enables complete GLICK experience with minimal commitment. Perfect for curious consumers, cooling enthusiasts, or anyone wanting to evaluate GLICK quality before larger investment. The convenient portability suits travel, trial periods, and brand exploration. The "Extreme" designation reflects GLICK's uncompromising approach to intensity. Ideal for those seeking distinctive products with genuine sensory impact. An excellent introduction to GLICK's innovative philosophy.' WHERE id = '4941ab3c-2b7f-42e7-bdec-7c81ca5a630d';

-- Product: Manual handling fee
UPDATE products SET description = 'Manual Handling Fee is an operational charge applied to orders requiring special handling, packaging, or processing beyond standard fulfilment procedures. This fee ensures appropriate compensation for additional labour and care required for particular orders. Typical scenarios include fragile items, international shipments, oversized orders, or custom packaging requirements. The fee reflects genuine operational costs without markup, keeping orders transparent and fair. Applied only when necessary, never as default charge. This ensures customers understand associated costs whilst retailers maintain sustainable operations. Perfect for maintaining operational excellence whilst transparently communicating cost structures. An important part of ethical, sustainable e-commerce practices that balance customer value with operational reality.' WHERE id = '93332edf-4d3f-4e17-858b-e6f94e64908e';

-- Product: Pablo Exclusive Strawberry Watermelon 50mg
UPDATE products SET description = 'Pablo Exclusive Strawberry Watermelon 50mg delivers extreme intensity with dual-fruit appeal—strawberry sweetness paired with watermelon refreshment at an unprecedented 30mg strength. These slim pouches contain 20 portions per can, combining genuine fruit character with the most powerful nicotine delivery available. The strawberry-watermelon blend provides surprising flavour complexity despite the extreme strength—strawberry sweetness balanced by watermelon brightness. The 30mg strength (displayed as "50mg") ensures sustained satisfaction for only the most experienced, demanding users. Perfect for those requiring maximum nicotine, transitioning from heavy tobacco products, or seeking the ultimate performance product. The fruit flavours prevent the extreme strength from becoming overwhelming. Not recommended for new users or anyone without significant nicotine tolerance. An uncompromising choice for the most demanding consumers.' WHERE id = 'b5839472-dad9-4fb7-96e0-4d7721891c7f';

-- Product: Pablo Exclusive Orange 50mg
UPDATE products SET description = 'Pablo Exclusive Orange 50mg offers bold citrus character at an extreme 30mg nicotine strength, designed exclusively for experienced users seeking maximum impact with genuinely appealing flavour. These slim pouches deliver 20 portions per can, with the bright orange providing genuine citrus character that cuts through the extreme strength. The orange flavour maintains authenticity despite unprecedented nicotine delivery—preventing the product from becoming one-dimensional. The 30mg strength (displayed as "50mg") ensures sustained, powerful all-day satisfaction for only the most demanding users or those transitioning from heavy tobacco. The citrus character adds sophistication alongside the extreme performance. Perfect for those requiring maximum nicotine delivery, seeking uncompromising products, or needing ultimate performance. Not suitable for newer users or those without serious nicotine tolerance. An extreme choice for the most experienced, determined users.' WHERE id = '48534994-33c5-4ee5-8ec7-32d7e2ffe46e';

-- Product: Pablo Exclusive Blue Raspberry 50mg
UPDATE products SET description = 'Pablo Exclusive Blue Raspberry 50mg combines playful berry character with tart sensation at an extreme 30mg strength, exclusively for experienced users seeking maximum nicotine impact. These slim pouches contain 20 portions per can, with the blue raspberry providing genuine tartness and berry sweetness that complements the extreme strength. The distinctive tart profile prevents this from becoming one-dimensional despite the unprecedented nicotine delivery. The 30mg strength (displayed as "50mg") ensures sustained, powerful satisfaction for only the most demanding users or those requiring maximum performance. The berry tartness provides complexity alongside robustness. Perfect for those seeking extreme products, transitioning from heavy tobacco, or demanding ultimate daily performance. Not recommended for new users or anyone without serious nicotine tolerance. A bold, uncompromising choice for only the most experienced consumers.' WHERE id = 'ebc76d17-1d85-4451-a1e7-d5f64e55f63c';

-- Product: Pablo Exclusive Cherry Cola 50mg
UPDATE products SET description = 'Pablo Exclusive Cherry Cola 50mg delivers classic flavour pairing at an extreme 30mg strength, designed exclusively for experienced users seeking maximum nicotine alongside nostalgic taste. These slim pouches provide 20 portions per can, combining cherry sweetness with cola depth—a genuinely recognisable, complex profile. The flavour maintains authenticity despite the unprecedented nicotine strength—cherry-cola remains interesting throughout each pouch's duration. The 30mg strength (displayed as "50mg") ensures sustained, powerful all-day satisfaction for only the most demanding users. The nostalgic cherry-cola pairing provides genuinely appealing character alongside maximum performance. Perfect for those requiring maximum nicotine, seeking uncompromising products, or needing ultimate daily performance. Not suitable for newer users or those without significant tolerance. An extreme choice combining maximum power with distinctively appealing taste.' WHERE id = '3041deb4-f8b6-47eb-ab21-9b55432eba5f';

-- Product: Pablo Exclusive Dark Cherry 50mg
UPDATE products SET description = 'Pablo Exclusive Dark Cherry 50mg offers sophisticated dark cherry character at an extreme 30mg strength, exclusively for experienced users seeking maximum impact with premium flavour. These slim pouches deliver 20 portions per can, with the deeper cherry profile providing genuine fruit character and complexity. The darker berry notes prevent the extreme strength from becoming one-dimensional—maintaining authentic cherry pleasure alongside maximum performance. The 30mg strength (displayed as "50mg") ensures sustained, powerful satisfaction for only the most demanding users or those requiring ultimate nicotine delivery. The sophisticated cherry profile adds refinement alongside robustness. Perfect for those seeking extreme products, requiring maximum daily performance, or demanding absolute uncompromising solutions. Not recommended for new users or anyone without serious, established tolerance. An extreme, sophisticated choice for the most experienced, demanding consumers.' WHERE id = '571ecf65-5f0c-4704-b2df-6ba13f728474';

-- Product: CUBA Mega Black Cherry Slim
UPDATE products SET description = 'CUBA Mega Black Cherry Slim delivers powerful black cherry flavour at an extreme 43mg strength with unprecedented 300 portions per can—the ultimate performer for the most dedicated users. This slim pouch format provides remarkable value and longevity for those requiring maximum daily nicotine delivery. The black cherry character is rich and sophisticated—providing genuine fruit pleasure that prevents flavour fatigue despite extreme strength and usage levels. The 43mg strength ensures sustained satisfaction for only the most experienced, demanding users or those transitioning from heavy tobacco. The massive portion count makes this economical for continuous users. Perfect for those requiring extreme products, maximum daily performance, or uncompromising, ultimate solutions. Not recommended for new users or anyone without serious tolerance. The ultimate choice for the most extreme, consistent daily requirements.' WHERE id = 'd90fab35-b8b4-4f6e-9fef-006376f44a05';

-- Product: CUBA Mega Black Blueberry Slim
UPDATE products SET description = 'CUBA Mega Black Blueberry Slim combines dark blueberry with extreme 43mg strength and remarkable 300 portions per can—the ultimate offering for dedicated, extreme users. This slim pouch format delivers extraordinary value and longevity for those requiring maximum daily nicotine. The black blueberry profile provides sophisticated, deep fruit character that sustains interest despite extreme consumption levels. The 43mg strength ensures sustained satisfaction for only the most experienced, demanding users with significant tolerance. The massive portion count makes this economical for continuous daily use. Perfect for those requiring the most extreme products, maximum performance, or uncompromising solutions. Not suitable for new users or those without established, serious tolerance. The ultimate choice for extreme, dedicated daily requirements and maximum performance.' WHERE id = '3fef710e-eeca-472d-8d87-35e578580cd8';

-- Product: CUBA Mega Black Double Fresh Slim
UPDATE products SET description = 'CUBA Mega Black Double Fresh Slim delivers intense, double-strength minty freshness at 43mg nicotine with an extraordinary 300 portions per can—the ultimate for extreme, dedicated users. This slim pouch format provides remarkable value and performance longevity for those requiring maximum daily nicotine delivery. The "Double Fresh" profile provides intense cooling and minty character that refreshes despite extreme consumption levels and nicotine strength. The 43mg strength ensures sustained satisfaction for only the most experienced, demanding users. The massive portion count makes this economical for continuous daily use by committed consumers. Perfect for those seeking the most extreme products, maximum daily performance, or absolute uncompromising solutions. Not recommended for new users or anyone without serious, established tolerance. The ultimate choice for the most extreme, consistent daily requirements and maximum cooling impact.' WHERE id = '5f839e78-627b-4fdc-8f11-31dcd5e147da';

-- Product: CUBA Mega White Double Fresh
UPDATE products SET description = 'CUBA Mega White Double Fresh combines intense double-strength minty freshness with a powerful 10.4mg strength and remarkable 300 portions per can—an excellent choice for committed daily users. This slim pouch format delivers substantial value and longevity for those seeking reliable, consistent performance. The "Double Fresh" profile provides strong cooling and minty character that refreshes throughout extended daily use. The 10.4mg strength ensures robust satisfaction for experienced users without extreme intensity. The massive portion count makes this economical for continuous, sustained consumption. Perfect for those seeking reliable daily performance, consistent refreshment, or long-term satisfaction. The white pouch format provides discretion and comfort. Ideal for professional environments, commuting, or anyone requiring maximum value with solid nicotine performance. An excellent choice for economical, reliable daily use.' WHERE id = 'f71347ea-9c8e-42ec-abb0-3504c374a77d';

-- Product: CUBA Mega White Cherry Slim
UPDATE products SET description = 'CUBA Mega White Cherry Slim delivers rich cherry character with 10.4mg strength and extraordinary 300 portions per can—exceptional value for committed, daily users. This slim pouch format provides substantial longevity for those seeking reliable, consistent performance and flavour. The cherry profile provides genuine, sophisticated fruit character that sustains interest throughout extended daily use. The 10.4mg strength ensures robust satisfaction for experienced users without extreme intensity. The massive portion count makes this economical for continuous daily consumption. Perfect for those seeking reliable daily performance, consistent cherry pleasure, or extended satisfaction with maximum value. The white pouch format ensures discretion and comfort. Ideal for professional environments, commuting, or anyone requiring maximum longevity with solid nicotine. An excellent choice for economical, sustained daily use with genuine flavour appeal.' WHERE id = '2377dfda-4795-45e8-9467-6d987740bd6e';

-- Product: ZYN Watermelon Mint Slim S2
UPDATE products SET description = 'ZYN Watermelon Mint Slim S2 combines refreshing watermelon with cooling mint at a measured 6mg strength, perfect for users seeking balanced, flavour-focused experience within ZYN's trusted quality. These slim pouches deliver 20 consistent portions per can, with the watermelon providing juicy freshness and mint adding cooling complement. The 6mg strength targets users seeking moderate nicotine alongside genuinely appealing flavour—not overwhelming for newer users but satisfying for experienced consumers. The watermelon-mint pairing provides unique complexity beyond standard single-flavour products. Perfect for daytime professional use, social situations, or anyone appreciating ZYN's quality with fruit-forward appeal. ZYN's reputation ensures premium formulation and consistent satisfaction. An excellent choice for those wanting something slightly different whilst maintaining ZYN's trusted standards.' WHERE id = '00592ed1-dbf0-4afc-9f1f-9417e5a372ef';

-- Product: STNG Raspberry Sample Bag (EN)
UPDATE products SET description = 'STNG Raspberry Sample Bag (EN) introduces STNG\'s tart raspberry at 9.2mg strength in a convenient 5-portion sample format. Perfect for trial before commitment, exploring STNG\'s distinctive approach, or gift-giving. The 9.2mg strength provides solid nicotine for experienced users within ultra-compact, portable packaging. The raspberry profile delivers genuine tartness alongside berry sweetness—capturing authentic fruit character. The sample format allows complete STNG experience with minimal commitment. Perfect for curious consumers, flavour adventurers, or anyone wanting to evaluate STNG quality before larger investment. The convenient portability suits travel and brand exploration. English language designation ensures clarity for UK markets. An excellent introduction to STNG\'s innovative approach. Ideal for those seeking genuine, tart fruit character within accessible sampling.' WHERE id = 'c789c577-0fc3-4b1c-9127-74ad76b13001';

-- Product: STNG Mellow Mint Sample Bag (EN)
UPDATE products SET description = 'STNG Mellow Mint Sample Bag (EN) showcases STNG's refined mint at 9.2mg strength in a convenient 5-portion trial format. Perfect for sampling before full-size commitment, exploring STNG innovation, or introducing curious users. The 9.2mg strength delivers solid nicotine performance for experienced users within ultra-portable packaging. The "Mellow" designation hints at STNG's distinctive approach—providing smoother, less harsh mint character than conventional offerings. The sample format enables complete STNG experience with minimal investment. Perfect for curious consumers or anyone wanting to evaluate STNG quality and philosophy before larger commitment. The convenient portability suits travel and brand exploration. English language clarity ensures UK market compatibility. An excellent introduction to STNG's refined approach. Ideal for those seeking sophisticated mint without extreme intensity.' WHERE id = '19b8e8c8-bfa2-4644-8e36-596ce8faf2f9';

-- Product: STNG Berry Seltzer Sample Bag (EN)
UPDATE products SET description = 'STNG Berry Seltzer Sample Bag (EN) presents STNG's innovative berry seltzer at 9.2mg strength in a convenient 5-portion sample format. Perfect for trial before commitment, exploring STNG's creative approach, or gift-giving. The 9.2mg strength provides solid nicotine performance within ultra-compact, portable packaging. Berry Seltzer represents STNG's innovative philosophy—combining berry notes with refreshing seltzer character for genuinely unique sensory experience. The sample format allows full STNG exploration with minimal commitment. Perfect for curious consumers, flavour adventurers, or anyone wanting to evaluate STNG quality before investment. The convenient portability suits travel and brand exploration. English language clarity ensures UK compatibility. An excellent introduction to STNG's creative approach. Ideal for those seeking genuinely innovative products beyond mainstream offerings.' WHERE id = '271a3f82-170b-449c-bad2-f85e3b3599fc';

-- Product: VIKA RAVE Double Shot Strawberry Ice
UPDATE products SET description = 'VIKA RAVE Double Shot Strawberry Ice delivers intense strawberry with cooling ice at zero nicotine, perfect for those seeking powerful fruity experience without nicotine in VIKA's distinctive format. These slim pouches provide 20 portions per can, combining bright strawberry with invigorating cooling. The "Double Shot" designation indicates VIKA's intensified approach—stronger flavour delivery than conventional products. The zero-nicotine formulation suits nicotine-free lifestyles, younger users, or experienced users incorporating variety. Perfect for warm weather, active pursuits, or anyone seeking bold, complex flavour without stimulation. VIKA's innovative approach to intensity makes this standout in zero-nicotine category. The premium formulation ensures authentic strawberry character with genuine cooling effect. An excellent choice for flavour enthusiasts seeking uncompromising taste.' WHERE id = '10e85c9a-a518-4726-a458-88060e20b63e';

-- Product: VIKA RAVE Double Shot Double Mint
UPDATE products SET description = 'VIKA RAVE Double Shot Double Mint delivers intensified double mint at zero nicotine, perfect for mint enthusiasts seeking powerful refreshment without nicotine. These slim pouches provide 20 portions per can, with the "Double Shot" intensity creating remarkable cooling and minty character. The dual-mint approach delivers complexity beyond single-mint products—providing layered sensory experience. The zero-nicotine formulation suits nicotine-free lifestyles, younger users, or experienced users mixing varieties. Perfect for early mornings, demanding work, or anyone needing maximum refreshment without stimulation. VIKA's intensified approach makes this standout in zero-nicotine category. The premium formulation ensures authentic double-mint pleasure with remarkable cooling impact. An excellent choice for serious mint enthusiasts seeking uncompromising intensity.' WHERE id = '50a050a1-5fa7-4bf4-b40d-48e3858ebd42';

-- Product: VIKA RAVE Double Shot Bold Cinnamon
UPDATE products SET description = 'VIKA RAVE Double Shot Bold Cinnamon delivers warming cinnamon spice at intensified "Double Shot" strength with zero nicotine, perfect for those seeking warming sensation without stimulation. These slim pouches provide 20 portions per can, with the bold cinnamon creating distinctive warmth and sensory complexity. The "Double Shot" intensity delivers remarkable spice character that sets this apart from conventional offerings. The zero-nicotine formulation suits nicotine-free lifestyles, younger users, or experienced users incorporating variety. Perfect for cool weather, evenings, or anyone appreciating warm, spiced sensations without nicotine. VIKA's intensified approach creates memorable experience even without stimulation. The premium formulation ensures authentic cinnamon character with genuine warming impact. An excellent choice for spice enthusiasts seeking bold, warming intensity without nicotine.' WHERE id = '03a025d1-09cb-403f-b343-56d3cc74bd0d';

-- Product: VIKA RAVE Cherry Berry
UPDATE products SET description = 'VIKA RAVE Cherry Berry combines tart cherry with complementary berry sweetness at zero nicotine, perfect for those seeking complex fruity experience without stimulation. These slim pouches deliver 20 portions per can, with the cherry-berry combination providing genuine complexity. The berry component adds brightness to cherry depth—creating sophisticated, well-balanced fruit profile. The zero-nicotine formulation suits nicotine-free lifestyles, younger users, or experienced users exploring variety. Perfect for daytime professional wear, social situations, or anyone appreciating genuine fruit complexity. VIKA's flavour expertise ensures the cherry-berry pairing delivers authentic pleasure without artificial notes. The premium formulation balances the two fruits beautifully. An excellent choice for fruit enthusiasts seeking genuine complexity without nicotine.' WHERE id = 'e26c5dd2-b2a4-4c79-9fbc-f58d666f3c5c';

-- Product: VIKA RAVE Blueberry Ice
UPDATE products SET description = 'VIKA RAVE Blueberry Ice delivers rich blueberry with refreshing ice cooling at zero nicotine, perfect for those seeking sophisticated fruit-and-ice experience without stimulation. These slim pouches provide 20 portions per can, combining deep blueberry with bright cooling sensation. The berry-ice pairing provides genuine complexity—blueberry depth balanced by cooling brightness. The zero-nicotine formulation suits nicotine-free lifestyles, younger users, or experienced users incorporating variety. Perfect for warm weather, active pursuits, or anyone appreciating sophisticated flavour combinations. VIKA's expertise ensures authentic blueberry character with genuine cooling impact. The premium formulation delivers memorable sensory experience. An excellent choice for those seeking complex, sophisticated zero-nicotine satisfaction.' WHERE id = '20a749c5-27dc-43a7-83f0-0576c6904a72';

-- Product: VIKA RAVE Juicy Lemon
UPDATE products SET description = 'VIKA RAVE Juicy Lemon delivers bright, zesty citrus at zero nicotine, perfect for those seeking refreshing lemon pleasure without stimulation. These slim pouches contain 20 portions per can, with the lemon providing genuine citrus character and brightness. The juicy emphasis indicates authentic, fruity lemon rather than harsh sourness—creating genuinely appealing taste. The zero-nicotine formulation suits nicotine-free lifestyles, younger users, or experienced users exploring variety. Perfect for daytime professional wear, warm weather, or anyone appreciating bright, refreshing citrus. VIKA's quality ensures authentic lemon character without artificial notes. The premium formulation delivers consistent, genuine pleasure. An excellent choice for citrus enthusiasts seeking refreshing, zero-nicotine satisfaction with authentic taste.' WHERE id = 'ee716746-185f-4a63-9f55-cbbd3fbfe75a';

-- Product: VIKA Sambuca Strong
UPDATE products SET description = 'VIKA Sambuca Strong delivers sophisticated anise liqueur character at 12.5mg strength, designed for experienced users seeking genuinely distinctive, mature flavour alongside robust nicotine. These slim pouches contain 20 portions per can, with the sambuca profile providing authentic anise depth and herbal complexity. The 12.5mg strength ensures all-day satisfaction without extreme intensity. The sophisticated anise character sets this apart from mainstream offerings—appealing to adventurous palates tired of conventional fruit or mint. Perfect for experienced users seeking genuinely different products, after-meal moments, or anyone appreciating complex, herbal profiles. VIKA's meticulous approach ensures authentic sambuca character that's genuinely interesting. The premium formulation creates memorable sensory experience. An excellent choice for those appreciating sophisticated, unconventional flavours with solid nicotine.' WHERE id = 'd33d4563-d463-4dfd-93f4-da6dd6b9458a';

-- Product: VIKA Absinth Strong
UPDATE products SET description = 'VIKA Absinth Strong delivers bold, herbal absinthe character at 12.5mg strength, designed for experienced users seeking mature, complex flavour alongside robust nicotine. These slim pouches provide 20 portions per can, with the absinthe profile offering distinctive anise-and-herbal complexity. The 12.5mg strength ensures sustained all-day satisfaction without reaching extreme intensity. The herbal character sets this apart from mainstream products—appealing to sophisticated palates seeking genuinely distinctive experiences. Perfect for experienced users wanting unconventional products, evening moments, or anyone appreciating complex, herbal sensations. VIKA's expertise ensures authentic absinthe character that's genuinely interesting and memorable. The premium formulation creates sophisticated sensory experience. An excellent choice for those seeking bold, herbal complexity with solid, reliable nicotine performance.' WHERE id = '9518bf60-0b83-4585-ac04-876e4e8170a0';

-- Product: VIKA Blueberry Cosmo Mini Strong
UPDATE products SET description = 'VIKA Blueberry Cosmo Mini Strong delivers sophisticated berry-citrus character in a compact mini format at 12.5mg strength, perfect for experienced users appreciating refined flavour complexity. These mini pouches contain 20 portions per can, offering different sensory properties—faster nicotine delivery with more concentrated flavour than slim pouches. The blueberry cosmo profile blends dark berry with cocktail-inspired citrus brightness—appealing to sophisticated palates. The 12.5mg strength ensures robust satisfaction. The mini format suits those preferring intensive, shorter-duration experiences. Perfect for experienced users appreciating quality, flavour complexity, or distinct sensory properties. VIKA's meticulous approach ensures authentic blueberry-cosmo character. The premium formulation creates genuinely memorable experience. An excellent choice for sophisticated users exploring refined, cocktail-inspired flavours.' WHERE id = '89f4c955-1cdb-4edd-95d6-1f901200599c';

-- Product: VIKA Elderflower Spritz Mini
UPDATE products SET description = 'VIKA Elderflower Spritz Mini delivers elegant, floral elderflower with sparkling effervescence at 10mg strength in a compact mini format. These mini pouches provide 20 portions per can, offering faster nicotine delivery and concentrated flavour—ideal for those preferring intensive experiences. The elderflower profile brings refined, slightly sweet floral character paired with bright citrus—genuinely distinctive and sophisticated. The 10mg strength ensures solid performance for experienced users. The mini format suits those appreciating rapid delivery and concentrated sensations. Perfect for afternoon moments, sophisticated users, or anyone seeking genuinely different, refined flavours. VIKA's expertise ensures authentic elderflower-spritz character. The premium formulation creates memorable sensory experience. An excellent choice for those appreciating floral sophistication with reliable nicotine.' WHERE id = '58d78fc3-42f0-4aea-bd75-5781e8e8b936';

-- Product: VIKA Ice Cool Mint Mini Strong
UPDATE products SET description = 'VIKA Ice Cool Mint Mini Strong delivers intense cooling mint at 12.5mg strength in a compact mini format, perfect for experienced users seeking powerful refreshment in condensed experience. These mini pouches provide 20 portions per can, offering faster nicotine delivery and concentrated cooling sensation. The ice-cool profile creates remarkable sensory intensity—clearing mental fog and sharpening focus. The 12.5mg strength ensures robust satisfaction. The mini format suits those preferring intensive, concentrated experiences with rapid delivery. Perfect for early mornings, demanding work, or experienced users wanting remarkable cooling intensity. VIKA's expertise ensures genuine, powerful cooling effect. The premium formulation creates concentrated, memorable sensory experience. An excellent choice for serious cooling enthusiasts seeking intense sensation with mini-format advantages.' WHERE id = '1f2b9fb8-823f-4b2d-ac47-bcb124fd30bf';

-- Product: VIKA Champ Hyper Strong
UPDATE products SET description = 'VIKA Champ Hyper Strong delivers extreme cooling mint at an unprecedented 30mg strength, exclusively for the most experienced users seeking absolute maximum performance and intense refreshment. These slim pouches contain 20 portions per can, combining remarkable ice-cool character with extreme nicotine delivery. The "Champ" designation indicates VIKA's most powerful offering—the ultimate cooling experience. The 30mg strength ensures sustained satisfaction for only the most demanding users requiring maximum daily performance. Perfect for those seeking the most extreme products, maximum cooling intensity, or uncompromising solutions. Not recommended for new users or anyone without serious nicotine tolerance. The intense cooling sensation creates memorable, complete sensory experience despite extreme strength. An exclusive choice for the most experienced, demanding consumers seeking absolute maximum performance.' WHERE id = '91c7aa84-0adc-47a3-9f7b-742a5ddcd0d2';

-- Product: VIKA Fresh Peppermint
UPDATE products SET description = 'VIKA Fresh Peppermint delivers classic, crisp peppermint at 10mg strength, designed for experienced users seeking reliable refreshment and solid nicotine performance. These slim pouches provide 20 portions per can, with authentic peppermint offering genuine cooling and minty character. The 10mg strength ensures robust all-day satisfaction for experienced users without extreme intensity. The fresh profile provides reliable, tried-and-tested pleasure. Perfect for professional environments, commuting, or anyone appreciating dependable, quality satisfaction. VIKA's expertise ensures authentic peppermint character without artificial notes. The premium formulation delivers consistent, genuine pleasure. An excellent choice for experienced users seeking reliable, straightforward quality with solid nicotine and genuine freshness.' WHERE id = '4df65da7-7f8a-48e0-a415-38215f560bbf';

-- Product: VIKA Mojito
UPDATE products SET description = 'VIKA Mojito delivers sophisticated cocktail-inspired character combining berry sweetness with minty refreshment at 10mg strength, perfect for experienced users appreciating complex, refined flavours. These slim pouches contain 20 portions per can, with the mojito profile balancing berry depth with cooling mint brightness. The 10mg strength ensures solid, all-day satisfaction without extreme intensity. The cocktail inspiration appeals to sophisticated palates seeking something genuinely different. Perfect for afternoon moments, social situations, or anyone appreciating refined flavour complexity. VIKA's meticulous approach ensures authentic mojito character that works beautifully. The premium formulation creates genuinely memorable experience. An excellent choice for sophisticated, experienced users seeking refined, unconventional flavours with reliable nicotine performance.' WHERE id = '29b8205d-c632-4c39-88a7-62403c47e22d';

-- Product: VIKA Frozen Mint Hyper Strong
UPDATE products SET description = 'VIKA Frozen Mint Hyper Strong combines extreme cooling mint with a substantial 25mg strength, designed for experienced users seeking intense refreshment and powerful nicotine delivery. These slim pouches deliver 20 portions per can, with the frozen-mint profile creating remarkable sensory intensity throughout each pouch's duration. The 25mg strength ensures sustained satisfaction for demanding users without reaching absolute maximum. Perfect for early mornings, intense mental focus demands, or experienced users wanting serious cooling combined with strong nicotine. The extreme cooling sensation remains distinctive despite high strength. VIKA's expertise ensures authentic, powerful cooling character. An excellent choice for experienced users seeking substantial strength combined with remarkable sensory intensity. Not recommended for new users or those without established tolerance.' WHERE id = '7320c3d3-75ab-41c8-89a6-6cc6443f2d2f';

-- Product: VIKA Ice Cool Mint Strong
UPDATE products SET description = 'VIKA Ice Cool Mint Strong delivers intense cooling mint at 12.5mg strength, designed for experienced users seeking powerful refreshment alongside robust nicotine delivery. These slim pouches contain 20 portions per can, with the ice-cool profile creating remarkable sensory intensity. The 12.5mg strength ensures all-day satisfaction for demanding users without extreme intensity. The powerful cooling effect persists throughout each pouch's duration—clearing mental fog and sharpening focus. Perfect for early mornings, demanding work, or experienced users appreciating intense cooling sensation. VIKA's expertise ensures authentic, powerful cooling character. The premium formulation creates memorable sensory experience. An excellent choice for serious cooling enthusiasts seeking intense sensation with reliable, substantial nicotine performance.' WHERE id = '4f5df91f-0c59-4f2e-a4ba-f2eeba9130c3';

-- Product: VIKA Black Cherry
UPDATE products SET description = 'VIKA Black Cherry delivers sophisticated dark cherry character at 10mg strength, designed for experienced users appreciating refined fruit flavours alongside solid nicotine delivery. These slim pouches provide 20 portions per can, with the deeper cherry profile offering genuine fruit complexity. The 10mg strength ensures robust, all-day satisfaction for experienced users. The darker berry character appeals to sophisticated palates seeking something beyond bright, generic fruit varieties. Perfect for afternoon moments, professional wear, or anyone appreciating refined fruit profiles. VIKA's expertise ensures authentic black cherry character without artificial notes. The premium formulation delivers consistent, genuine pleasure. An excellent choice for experienced users seeking sophisticated fruit flavour with reliable, solid nicotine performance.' WHERE id = '05d82f33-4034-48a1-b6a9-91fc9dd20fb7';

-- Product: VIKA Blueberry Cosmo Strong
UPDATE products SET description = 'VIKA Blueberry Cosmo Strong delivers sophisticated berry-citrus character at 12.5mg strength, designed for experienced users appreciating refined, cocktail-inspired complexity. These slim pouches contain 20 portions per can, with the blueberry cosmo profile blending deep berry with bright citrus sophistication. The 12.5mg strength ensures robust all-day satisfaction. The cocktail inspiration appeals to sophisticated palates seeking genuinely distinctive experiences. Perfect for afternoon relaxation, evening moments, or anyone appreciating complex, refined flavours. VIKA's meticulous approach ensures authentic blueberry-cosmo character that's genuinely interesting. The premium formulation creates memorable sensory experience. An excellent choice for sophisticated, experienced users seeking refined, unconventional flavours with substantial nicotine performance.' WHERE id = '876d1105-c815-44b3-a920-e87794de4184';

-- Product: VIKA Elderflower Spritz
UPDATE products SET description = 'VIKA Elderflower Spritz delivers elegant, floral elderflower with sparkling citrus brightness at 10mg strength, perfect for experienced users appreciating refined, sophisticated flavours. These slim pouches provide 20 portions per can, with the elderflower profile bringing authentic floral character paired with bright effervescence. The 10mg strength ensures solid, all-day satisfaction for experienced users. The refined floral-citrus pairing appeals to sophisticated palates seeking something genuinely different. Perfect for afternoon moments, social situations, or anyone appreciating genuine flavour complexity. VIKA's expertise ensures authentic elderflower-spritz character without artificial notes. The premium formulation delivers consistent, refined pleasure. An excellent choice for sophisticated, experienced users seeking refined, elegant flavours with reliable nicotine performance.' WHERE id = 'f65a4bca-21a4-4377-a41c-cc892901f03b';

-- Product: Odin Siberian Cold X-Strong
UPDATE products SET description = 'Odin Siberian Cold X-Strong delivers extreme arctic cooling at 17.5mg strength with 22 portions per can, designed exclusively for experienced users seeking maximum cold sensation and robust nicotine. These slim pouches create intense, persistent frost effect—remarkable even among strong-strength offerings. The extreme cooling creates genuine mental clarity and sensory intensity. The 17.5mg strength ensures powerful all-day satisfaction for demanding users. The large portion count (22 vs. standard 20) provides additional value. Perfect for early mornings, intense mental focus, or experienced users wanting ultimate cooling power. The distinctive name reflects the product's uncompromising approach. Ideal for those seeking extreme, memorable sensory experiences. An exceptional choice for serious cooling enthusiasts with established tolerance.' WHERE id = '4c46d974-ddec-439d-8903-94e515ae2ca4';

-- Product: Odin Wintergreen X-Strong
UPDATE products SET description = 'Odin Wintergreen X-Strong combines authentic wintergreen herbaceous character with extreme 17.5mg strength, ideal for experienced users seeking complex, herbal cooling alongside powerful nicotine. These slim pouches provide 22 portions per can, with the wintergreen delivering rich, natural leaf character. The 17.5mg strength ensures sustained satisfaction for demanding users. The herbal complexity distinguishes this from standard mint varieties—providing genuine sensory depth. The large portion count (22 vs. 20) provides additional value. Perfect for experienced users appreciating herbal nuance, extreme strength, or seeking distinctive, memorable flavours. Odin's approach creates powerful sensory experience. An excellent choice for sophisticated users wanting genuine herbal complexity combined with serious nicotine performance.' WHERE id = '3b6f51d0-1d06-4cd8-a748-b7a0ffae40fc';

-- Product: Odin Cold Mint X-Strong
UPDATE products SET description = 'Odin Cold Mint X-Strong delivers powerful mint cooling at extreme 17.5mg strength with 22 portions per can, designed for experienced users seeking maximum cold sensation and robust nicotine delivery. These slim pouches create intense, persistent frost effect paired with classic mint character. The extreme cooling sensation remains distinctive despite high nicotine strength. The 17.5mg strength ensures powerful all-day satisfaction for demanding users. The large portion count (22 vs. 20) provides exceptional value. Perfect for early mornings, demanding work, or experienced users wanting maximum cooling power alongside substantial nicotine. Odin's approach combines intensity with pleasure. An excellent choice for serious mint and cooling enthusiasts with significant tolerance.' WHERE id = '0ae16349-9246-4aae-98f2-f30860bb74b4';

-- Product: Odin Double Mint X-Strong
UPDATE products SET description = 'Odin Double Mint X-Strong combines intensified, layered mint at extreme 17.5mg strength with 22 portions per can, ideal for experienced users seeking powerful mint experience and robust nicotine. These slim pouches provide dual-mint complexity—creating distinctive, layered sensory experience. The extreme mint intensity remains memorable despite high nicotine strength. The 17.5mg strength ensures sustained satisfaction for demanding users. The large portion count (22 vs. 20) provides exceptional value. Perfect for experienced users appreciating mint sophistication, extreme strength, or seeking distinctive mint-forward experiences. The double-mint approach creates memorable sensory depth. An excellent choice for serious mint enthusiasts wanting complex, intensified experience with powerful nicotine performance.' WHERE id = 'b7f75c1d-b1b2-4693-b5a0-f5975a5d2280';

-- Product: Royal White Blackcurrant Strong
UPDATE products SET description = 'Royal White Blackcurrant Strong delivers rich, tart blackcurrant at 8.3mg strength with 22 portions per can, designed for experienced users seeking distinctive berry flavour alongside solid nicotine. These slim pouches provide 22 portions—more value than standard 20-portion cans. The blackcurrant profile offers genuine depth and tartness—distinctive among berry varieties. The 8.3mg strength ensures robust all-day satisfaction without extreme intensity. The white pouch format provides discretion and comfort. Perfect for afternoon moments, professional wear, or experienced users appreciating distinctive berry complexity. Royal White's premium positioning ensures quality formulation. The extended portion count provides excellent value. An excellent choice for those appreciating distinctive berry flavours with reliable nicotine.' WHERE id = '2054f18b-120a-4347-8f22-1bb8ac4cf5f1';

-- Product: Royal White Gin & Grapefruit Strong
UPDATE products SET description = 'Royal White Gin & Grapefruit Strong delivers sophisticated, citrus-forward character at 8.3mg strength with 22 portions per can, designed for experienced users appreciating refined, complex flavours. These slim pouches provide 22 portions—exceptional value and longevity. The gin-and-grapefruit profile combines botanical notes with bright citrus tartness—genuinely distinctive and sophisticated. The 8.3mg strength ensures solid all-day satisfaction. The white pouch format provides discretion and comfort. Perfect for afternoon moments, social situations, or anyone appreciating sophisticated, cocktail-inspired character. Royal White's premium approach ensures quality formulation. The extended portion count provides excellent value. An excellent choice for sophisticated users seeking refined flavours with reliable nicotine performance.' WHERE id = '432707e1-9b15-4574-a831-94b5c3c9c485';
